In [2]:
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))

Hello, TensorFlow!


In [4]:
my_list = [1,2,3] #cria uma lista de numeros

In [6]:
type(my_list)

list

In [9]:
import numpy as np

arr=np.array(my_list) #arr recebe a lista my_list tranformada em uma matriz

In [10]:
arr

array([1, 2, 3])

In [59]:
np.arange(5,18) #cria uma matriz com valores entre 5 e 18 (não incluindo este)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [22]:
np.arange(2,20, 2) #inicia no 2 até antes do 20 (não incluindo este) saltando de 2 em 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [14]:
np.zeros(8) #cria um vetor com 8 zeros

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,3)) #cria uma matriz de zeros com 5 linhas e 3 colunas

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.linspace(1,20, 10) #10 pontos igualmente espaçados entre 1 e 20

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [37]:
arr = np.random.randint(0,50,(4,4)) #cria uma matriz randomicamente 4x4 com valores de 0 a 50

In [38]:
arr

array([[ 6,  1, 42,  9],
       [12, 20, 45, 13],
       [12, 44, 29,  1],
       [11, 17,  3, 16]])

In [39]:
arr.max() #valor máximo da matriz arr

45

In [40]:
arr.min() #valor minimo da matriz arr

1

In [50]:
x = [[1,2,3],
    [4,5,6]]

In [51]:
x=np.array(x) #tranforma a lista x em uma matriz x

In [52]:
x.mean() #média dos valores da matriz x

3.5

In [54]:
x.argmax() #posição do valor máximo, veja que inicia na posição 0

5

In [60]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
vetor = [1,2,3,4,5,6,7,8,9] #cria uma lista chamada vetor

In [62]:
vetor=np.array(vetor) #vetor recebe 'vetor' como uma matriz

In [65]:
p = vetor.reshape(3,3) #p recebe a matriz remodelada de forma 3x3

In [66]:
p #imprime 'p' na tela

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
#diferença entre escalar, vetor, matriz e tensor

import tensorflow as tf
Scalar = tf.constant([2])
Vector = tf.constant([2,2,3])
Matrix = tf.constant([[2,2,3],[2,2,3],[2,2,3]])
Tensor = tf.constant([[[2,2,3],[2,2,3],[2,2,3]] , [[2,2,3],[2,2,3],[2,2,3]] , [[2,2,3],[2,2,3],[2,2,3]]])
with tf.Session() as session:
  result = session.run(Scalar)
  print "Scalar (1 entry) :\n %s \n" % result
  
  result = session.run(Vector)
  print "Vector (3 entries) :\n %s \n" % result
  
  result = session.run(Matrix)
  print "Matrix (3x3 entries) :\n %s \n" % result
  
  result = session.run(Tensor)
  print "Tensor (3x3x3 entries) :\n %s \n" % result

Scalar (1 entry) :
 [2] 

Vector (3 entries) :
 [2 2 3] 

Matrix (3x3 entries) :
 [[2 2 3]
 [2 2 3]
 [2 2 3]] 

Tensor (3x3x3 entries) :
 [[[2 2 3]
  [2 2 3]
  [2 2 3]]

 [[2 2 3]
  [2 2 3]
  [2 2 3]]

 [[2 2 3]
  [2 2 3]
  [2 2 3]]] 



In [19]:
#soma de matrizes usando a função tensorflow e usando operação matemática normal

Matrix_one = tf.constant([[1,1,1],[1,1,1],[1,1,1]])
Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

first_operation = tf.add(Matrix_one, Matrix_two)

second_operation = Matrix_one + Matrix_two

third_operation = tf.matmul(Matrix_one, Matrix_two)

with tf.Session() as session:
  
  result = session.run(first_operation)
  print "Defined using tensorflow function :"
  print(result)
  
  result = session.run(second_operation)
  print "Defined using normal expressions :"
  print(result)
  
  result = session.run(third_operation)
  print "Defined using tensorflow function :"
  print(result)

Defined using tensorflow function :
[[3 3 3]
 [3 3 3]
 [3 3 3]]
Defined using normal expressions :
[[3 3 3]
 [3 3 3]
 [3 3 3]]
Defined using tensorflow function :
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [24]:
#variables

state = tf.Variable(2) 

one = tf.constant(3)

new_value = tf.add(state, one)

update = tf.assign(state, new_value) #assign é atribuição

init_op = tf.global_variables_initializer() #inicialização

with tf.Session() as session:
  session.run(init_op)
  print(session.run(state))
  for _ in range(3):
    session.run(update)
    print(session.run(state))

2
5
8
11


In [42]:
#placeholders

a = tf.placeholder(tf.float32)

b = a*2

with tf.Session() as sess:
  result = sess.run(b, feed_dict={a:3.5})
  print result

7.0


In [48]:
#placeholders

c = tf.placeholder(tf.float32)

dictionary = {c:[ [[1,1,1],[1,1,1],[1,1,1]] , [[1,1,1],[1,1,1],[1,1,1]] , [[1,1,1],[1,1,1],[1,1,1]] ]}

d = c*4 

with tf.Session() as sess:
  result = sess.run(d, feed_dict=dictionary)
  print result

[[[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]]
